---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cosmolet
  namespace: network-system
  labels:
    app: cosmolet
    component: bgp-controller
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosmolet
  labels:
    app: cosmolet
    component: bgp-controller
rules:
# Core resources for service monitoring
- apiGroups: [""]
  resources: ["services", "services/status"]
  verbs: ["get", "list", "watch"]

- apiGroups: [""]
  resources: ["endpoints", "endpoints/status"]
  verbs: ["get", "list", "watch"]

# Node access for network monitoring and next-hop determination
- apiGroups: [""]
  resources: ["nodes", "nodes/status"]
  verbs: ["get", "list", "watch"]

# Pod monitoring for network policies and debugging
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "list", "watch"]

# Events for logging and debugging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# ConfigMaps for configuration updates
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["cosmolet-config", "frr-config"]

# Network policies monitoring
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]

# Leader election support
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

# Metrics and monitoring
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cosmolet
  labels:
    app: cosmolet
    component: bgp-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cosmolet
subjects:
- kind: ServiceAccount
  name: cosmolet
  namespace: network-system
