apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cosmolet.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cosmolet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cosmolet
    spec:
      serviceAccountName: {{ include "cosmolet.serviceAccountName" . }}
      hostNetwork: {{ .Values.daemonset.hostNetwork }}
      hostPID: {{ .Values.daemonset.hostPID }}
      containers:
      - name: cosmolet
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/cosmolet
        - name: frr-sockets
          mountPath: /var/run/frr
      volumes:
      - name: config
        configMap:
          name: {{ include "cosmolet.fullname" . }}-config
      - name: frr-sockets
        hostPath:
          path: /var/run/frr
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
