{{- if and .Values.serviceMonitor.enabled .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cosmolet.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cosmolet.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    path: {{ .Values.metrics.path }}
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace.name }}
  selector:
    matchLabels:
      {{- include "cosmolet.selectorLabels" . | nindent 6 }}
{{- end }}
