# Default values for cosmolet
replicaCount: 1

image:
  repository: cosmolet/cosmolet
  pullPolicy: IfNotPresent
  tag: ""

config:
  services:
    namespaces:
      - "default"
      - "kube-system"
  loopIntervalSeconds: 30
  bgp:
    enabled: true
  logging:
    level: "info"
    format: "text"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations:
  - operator: Exists
affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

rbac:
  create: true

securityContext:
  privileged: true
  runAsUser: 0

daemonset:
  hostNetwork: true
  hostPID: true
