services:
  namespaces:
    - "ingress-controller"

loop_interval_seconds: 3

bgp_mode: "connected"  # options: "dynamic" or "connected"

bgp:
  enabled: true
  asn: 65496

logging:
  level: "info"
  format: "text"

frr:
  socket_path: "/var/run/frr"

